### ISSUE TITLE
download-maven-plugin:1.6.1:wget failed: java.io.EOFException

### ISSUE THREAD

**Issue by git-surfer** [maven-download-plugin/maven-download-plugin#188]
I am downloading 5-10 different files using multiple wget in parallel. Most of the time files are downloaded correctly. Once in a while wget fails with following exception.

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.1:wget (download-artifact) on project common: Execution download-artifact of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.1:wget failed: java.io.EOFException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution download-artifact of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.1:wget failed: java.io.EOFException
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalStateException: java.io.EOFException
	at com.googlecode.download.maven.plugin.internal.cache.FileBackedIndex.loadFrom(FileBackedIndex.java:128)
	at com.googlecode.download.maven.plugin.internal.cache.FileBackedIndex.<init>(FileBackedIndex.java:52)
	at com.googlecode.download.maven.plugin.internal.cache.DownloadCache.<init>(DownloadCache.java:37)
	at com.googlecode.download.maven.plugin.internal.WGet.lambda$execute$0(WGet.java:338)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.googlecode.download.maven.plugin.internal.WGet.execute(WGet.java:336)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 21 more
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3017)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1576)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
	at com.googlecode.download.maven.plugin.internal.cache.FileBackedIndex.loadFrom(FileBackedIndex.java:124)
	... 27 more

**Comment by longtimeago** [comment]
@git-surfer Interesting ... are all those executions in a single maven (sub)module or in different?
Maybe, you could share some anonymized example?

**Comment by git-surfer** [comment]
Executions are in different maven (1 maven : 1 plugin).

**Comment by git-surfer** [comment]
New observation: Although failure are rare, the chances of failure increases if new files are downloaded which is not present in the plugin cache (${local-repo}/.cache) OR cache is cleared.

From the source code it seems that issue could be around locking of "index.ser".

**Comment by longtimeago** [comment]
@git-surfer yup ... that's because the lock on `index.ser` works when accessed from the same process
let me think how we could fix that.
Thanks for reporting!
